apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  type: NodePort  # 或 ClusterIP，根據需要調整
  selector:
    app: ollama
  ports:
    - port: 80
      targetPort: 11434
      nodePort: 30007  # 如果使用 NodePort